name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    


jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Clean the dist directory
      - name: Clean up dist directory
        run: rm -rf dist && mkdir dist
        
      # Generate the Snake animation files
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-red.svg
            dist/github-snake-red.svg?palette=github-dark
            dist/red.svg?color_snake=orange&color_dots=#400202,#9e0000,#f00000,#f54d05,#fba937

      # push the content of <build_dir> to a branch
      # Push the updated files to the output branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
